[note]
template = "default.md"

[tool]
fzf-line = "{{style 'white' title}}{{#each tags}} {{#style 'cyan'}} #{{this}}{{/style}}{{/each}} {{style 'white' body}}"
fzf-options = "--preview-label=VOCABULARIES --tiebreak begin --exact --tabstop 2 --height 100% --layout reverse-list --no-hscroll --preview-window top:60%:wrap"
