[group.vocabs]
paths = ["vocabs"]
[group.journal]
paths = ["journal"]
[group."inbox"]
paths = ["inbox"]
[group."permanent"]
paths = ["permanent"]

[group.journal.note]
filename = "{{format-date now}}"
template="daily.md"

[group."inbox".note]
template = "fleeting.md"
[group."permanent".note]
template = "permanent.md"

[group."permanent".extra]
